version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./deployment/production/django/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../.envs/.postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/fullchain1.pem:/fullchain1.pem:ro
      - ./nginx/privkey1.pem:/privkey1.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  redis:
    image: redis:7-alpine

  celery-worker:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    depends_on:
      - db
      - redis
      - web
    command: celery -A merovingian worker -l info

  celery-beat:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    depends_on:
      - db
      - redis
      - web
    command: celery -A merovingian beat -l info



volumes:
  postgres_data: {}

networks:
  default:
    name: merovingian
    external: true
