version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./deployment/production/django/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: {}
