version: '3'
services:
  web:
    build:
      context: ../..
      dockerfile: ./deployment/local/Dockerfile
    # network_mode: "host"
    ports:
      - 8000:8000
    volumes:
      - ../..:/app
    depends_on:
      - db
    environment:
      - HTTP_PROXY=http://127.0.0.1:8889/
      - HTTPS_PROXY=http://127.0.0.1:8889/

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    # network_mode: "host"

volumes:
  postgres_data: {}
